<?php

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'John Doe',
                'email' => 'john@email.com',
                'password' => '$2y$10$kTuo5IF.kmfgPgtA75lV/.ejdECoRbJZGqmLVsfl6f25bxzpDOQ.6',
                'role' => 'user',
                'phone_number' => NULL,
                'bio' => 'hello this john duo hhh',
                'skills' => NULL,
                'current_position' => NULL,
                'city' => NULL,
                'birthdate' => NULL,
                'github' => NULL,
                'linkedin' => NULL,
                'facebook' => NULL,
                'twitter' => NULL,
                'remember_token' => NULL,
                'created_at' => '2018-02-24 21:46:19',
                'updated_at' => '2018-03-20 15:36:51',
            ),
            1 => 
            array (
                'id' => 11,
                'name' => 'Souhail M',
                'email' => 'souhail.merroun@hotmail.com',
                'password' => '$2y$10$xvdqPHOaAGu/JZJoG3eNKuRZc3p7bXaiw890iGUB6Ah4e0w4wZHx.',
                'role' => 'admin',
                'phone_number' => '06 25 20 11 61',
                'bio' => 'Hi there, I am born in Tangier. I\'ve been passionate about building apps since high school!',
                'skills' => 'Laravel, Vue',
                'current_position' => 'Working in Casablanca at OSP S.A and studying Computer Science at Uopeople',
                'city' => 'Tangier',
                'birthdate' => '1996-05-23 00:00:00',
                'github' => 'https://github.com/souhailmerroun',
                'linkedin' => 'https://www.linkedin.com/in/souhailmerroun/',
                'facebook' => NULL,
                'twitter' => 'https://twitter.com/SouhailMerroun',
                'remember_token' => 'dvtzvX2Zb1nkldUnTeebYyWypGlIAC8AjqWOvGwcAK8GNqTkuRmheTrqbg70',
                'created_at' => '2018-02-24 23:43:26',
                'updated_at' => '2018-03-21 11:20:03',
            ),
            2 => 
            array (
                'id' => 31,
                'name' => 'Abdellah Chadidi',
                'email' => 'chadidi97@gmail.com',
                'password' => '$2y$10$0yey1w75WUqxoExmf4KR2.ai10epv0Tjq./Eo98h6V.agBoMjOpsG',
                'role' => 'user',
                'phone_number' => NULL,
                'bio' => NULL,
                'skills' => NULL,
                'current_position' => NULL,
                'city' => NULL,
                'birthdate' => NULL,
                'github' => NULL,
                'linkedin' => NULL,
                'facebook' => NULL,
                'twitter' => NULL,
                'remember_token' => NULL,
                'created_at' => '2018-02-26 20:05:41',
                'updated_at' => '2018-02-26 20:05:41',
            ),
            3 => 
            array (
                'id' => 41,
                'name' => 'Nourelhouda',
                'email' => 'Nourelhouda.el@gmail.com',
                'password' => '$2y$10$gAOIUzs76MjVloE6Z2Hm3.DLtvXWlj.RBLU7D6QhODHtrDFSQfpGu',
                'role' => 'user',
                'phone_number' => NULL,
                'bio' => NULL,
                'skills' => NULL,
                'current_position' => NULL,
                'city' => NULL,
                'birthdate' => NULL,
                'github' => NULL,
                'linkedin' => NULL,
                'facebook' => NULL,
                'twitter' => NULL,
                'remember_token' => NULL,
                'created_at' => '2018-02-27 16:19:39',
                'updated_at' => '2018-02-27 16:19:39',
            ),
            4 => 
            array (
                'id' => 51,
                'name' => 'Houda',
                'email' => 'houda.mouttalib@gmail.com',
                'password' => '$2y$10$2qS7qyj1vt71k0RV6FthCOGjUSQiGO9yEbkdTh7AoVDV6tbkFcMzK',
                'role' => 'user',
                'phone_number' => NULL,
                'bio' => NULL,
                'skills' => NULL,
                'current_position' => NULL,
                'city' => NULL,
                'birthdate' => NULL,
                'github' => NULL,
                'linkedin' => NULL,
                'facebook' => NULL,
                'twitter' => NULL,
                'remember_token' => NULL,
                'created_at' => '2018-03-20 12:06:25',
                'updated_at' => '2018-03-20 12:06:25',
            ),
            5 => 
            array (
                'id' => 61,
                'name' => 'Houssain Amrani',
                'email' => 'amranidev@gmail.com',
                'password' => '$2y$10$v3FNum6JaK7DlKEnOG/J5ODABO7bvQ/YNq.SQn8jThB5bE9VAU032',
                'role' => 'admin',
                'phone_number' => NULL,
                'bio' => NULL,
                'skills' => NULL,
                'current_position' => NULL,
                'city' => NULL,
                'birthdate' => NULL,
                'github' => NULL,
                'linkedin' => NULL,
                'facebook' => NULL,
                'twitter' => NULL,
                'remember_token' => NULL,
                'created_at' => '2018-03-20 12:06:41',
                'updated_at' => '2018-03-20 12:06:41',
            ),
            6 => 
            array (
                'id' => 71,
                'name' => 'Imtiyaz CHOUJAI',
                'email' => 'choujai.imtiyaz@gmail.com',
                'password' => '$2y$10$WUlHSDusMU8eaQMZz4MDqeHCMrc7RCmj6Iq3pqV/sLXXVWK5b5nh2',
                'role' => 'user',
                'phone_number' => NULL,
                'bio' => NULL,
                'skills' => NULL,
                'current_position' => NULL,
                'city' => NULL,
                'birthdate' => NULL,
                'github' => NULL,
                'linkedin' => NULL,
                'facebook' => NULL,
                'twitter' => NULL,
                'remember_token' => 'Coe1306WsLdUKNtmr8DN3rwXHArChgKMpxz5vZhWDdTo4jri4zVVdZY93NbO',
                'created_at' => '2018-03-20 12:37:36',
                'updated_at' => '2018-03-20 12:37:36',
            ),
            7 => 
            array (
                'id' => 81,
                'name' => 'Chrifi Alaoui Mehdi',
                'email' => 'tonextgeneration@gmail.com',
                'password' => '$2y$10$0gO8Pdr9N56aA1uWA9M3VOQFK2ObbaP50PrKQSMXJoIePR2bQ03M2',
                'role' => 'user',
                'phone_number' => NULL,
                'bio' => NULL,
                'skills' => NULL,
                'current_position' => NULL,
                'city' => NULL,
                'birthdate' => NULL,
                'github' => NULL,
                'linkedin' => NULL,
                'facebook' => NULL,
                'twitter' => NULL,
                'remember_token' => NULL,
                'created_at' => '2018-03-20 13:07:16',
                'updated_at' => '2018-03-20 13:07:16',
            ),
            8 => 
            array (
                'id' => 91,
                'name' => 'alexandre',
                'email' => 'kone.alexandr@gmail.com',
                'password' => '$2y$10$XcX.RBoe2iJdHkUrZl5f5.LG2tB37SnmA5IDrs7KUT8hGf3RM8dXm',
                'role' => 'user',
                'phone_number' => NULL,
                'bio' => NULL,
                'skills' => NULL,
                'current_position' => NULL,
                'city' => NULL,
                'birthdate' => NULL,
                'github' => NULL,
                'linkedin' => NULL,
                'facebook' => NULL,
                'twitter' => NULL,
                'remember_token' => NULL,
                'created_at' => '2018-03-20 13:38:52',
                'updated_at' => '2018-03-20 13:38:52',
            ),
            9 => 
            array (
                'id' => 101,
                'name' => 'Jihane',
                'email' => 'Benkhadra.jihane@gmail.com',
                'password' => '$2y$10$9teIwMw2triwpN3rEcfCX.7z5M17u6dvt5oUcV7dWlSjLYjpPMuJu',
                'role' => 'user',
                'phone_number' => NULL,
                'bio' => NULL,
                'skills' => NULL,
                'current_position' => NULL,
                'city' => NULL,
                'birthdate' => NULL,
                'github' => NULL,
                'linkedin' => NULL,
                'facebook' => NULL,
                'twitter' => NULL,
                'remember_token' => NULL,
                'created_at' => '2018-03-20 14:35:25',
                'updated_at' => '2018-03-20 14:35:25',
            ),
            10 => 
            array (
                'id' => 111,
                'name' => 'Mouad Fahsi Ben Sellam',
                'email' => 'mouad.fahsi@outlook.com',
                'password' => '$2y$10$kST0cRUnV.TyQeP7hsEVD.MJg0p31z.r8V0IvbS8GXV07KnQfxcQK',
                'role' => 'user',
                'phone_number' => NULL,
                'bio' => NULL,
                'skills' => NULL,
                'current_position' => NULL,
                'city' => NULL,
                'birthdate' => NULL,
                'github' => NULL,
                'linkedin' => NULL,
                'facebook' => NULL,
                'twitter' => NULL,
                'remember_token' => 'F40fx6RIQx95RLidYx7LZaaMea8loRqS0eDrQdNZOpEGuJmxRrpDJOjhCbz4',
                'created_at' => '2018-03-20 14:57:01',
                'updated_at' => '2018-03-20 14:57:01',
            ),
            11 => 
            array (
                'id' => 121,
                'name' => 'almokhtar bekkour',
                'email' => 'moktarb911@gmail.com',
                'password' => '$2y$10$v7bdI2nWAMijISohah.BNOU11dl1FD7Nq.T7nLDwQc.TRODQIJiZO',
                'role' => 'user',
                'phone_number' => NULL,
                'bio' => NULL,
                'skills' => NULL,
                'current_position' => NULL,
                'city' => NULL,
                'birthdate' => NULL,
                'github' => NULL,
                'linkedin' => NULL,
                'facebook' => NULL,
                'twitter' => NULL,
                'remember_token' => NULL,
                'created_at' => '2018-03-20 15:29:36',
                'updated_at' => '2018-03-20 15:29:36',
            ),
            12 => 
            array (
                'id' => 131,
                'name' => 'Nawfal',
                'email' => 'nawfalhaddi@gmail.com',
                'password' => '$2y$10$fZ2m5/6sg.0REtpja2pY.uhy0cgLcU4MEnpO8eIxo1oA8Ntgyv1pa',
                'role' => 'user',
                'phone_number' => NULL,
                'bio' => NULL,
                'skills' => NULL,
                'current_position' => NULL,
                'city' => NULL,
                'birthdate' => NULL,
                'github' => NULL,
                'linkedin' => NULL,
                'facebook' => NULL,
                'twitter' => NULL,
                'remember_token' => NULL,
                'created_at' => '2018-03-20 16:23:43',
                'updated_at' => '2018-03-20 16:23:43',
            ),
            13 => 
            array (
                'id' => 141,
                'name' => 'Saber El Harti',
                'email' => 'saberelharti@gmail.com',
                'password' => '$2y$10$2RguKuaOTsHr1PG0.dm57.T8jpgR0WK1VZ3Yd05gx1noaOEggaxc.',
                'role' => 'user',
                'phone_number' => NULL,
                'bio' => NULL,
                'skills' => NULL,
                'current_position' => NULL,
                'city' => NULL,
                'birthdate' => NULL,
                'github' => NULL,
                'linkedin' => NULL,
                'facebook' => NULL,
                'twitter' => NULL,
                'remember_token' => NULL,
                'created_at' => '2018-03-20 16:32:10',
                'updated_at' => '2018-03-20 16:32:10',
            ),
            14 => 
            array (
                'id' => 151,
                'name' => 'mohcineabkhar',
                'email' => 'mohcineabkhar.officail@gmail.com',
                'password' => '$2y$10$O6Pi9wfxMSTxB/4FIyEnvOmNlRwaUAKbSYCBhSac7xdX7FxEy5QYC',
                'role' => 'user',
                'phone_number' => NULL,
                'bio' => NULL,
                'skills' => NULL,
                'current_position' => NULL,
                'city' => NULL,
                'birthdate' => NULL,
                'github' => NULL,
                'linkedin' => NULL,
                'facebook' => NULL,
                'twitter' => NULL,
                'remember_token' => NULL,
                'created_at' => '2018-03-20 17:36:30',
                'updated_at' => '2018-03-20 17:36:30',
            ),
            15 => 
            array (
                'id' => 161,
                'name' => 'Metanas',
                'email' => 'com.com404@gmail.com',
                'password' => '$2y$10$UVd4GhtR6X.3.jN1CdwUv.Vn7JMFQ8oGEK5nAlqm7ynuNk7vHBJ6a',
                'role' => 'user',
                'phone_number' => NULL,
                'bio' => NULL,
                'skills' => NULL,
                'current_position' => NULL,
                'city' => NULL,
                'birthdate' => NULL,
                'github' => NULL,
                'linkedin' => NULL,
                'facebook' => NULL,
                'twitter' => NULL,
                'remember_token' => NULL,
                'created_at' => '2018-03-20 21:48:50',
                'updated_at' => '2018-03-20 21:48:50',
            ),
        ));
        
        
    }
}